### ISSUE TITLE
Problems adding/ load new '.obj' files

### ISSUE THREAD

**Issue by victorcs85** [andresoviedo/android-3D-model-viewer#13]
I am trying to load the following [template ](https://www.turbosquid.com/3d-models/3d-sede-tet-a-tet-model/391941) via "Load Model" option or add in the project assets. Both do not carry. 
The 3d model have '.obj' and '.mtl' files.
When trying to check the error in logcat, the error is printed and quickly cleaned (since the app restarta) thus making verification impossible.
I have tried other several .obj files and none are being uploaded only the files that already come with the project.
Is there any implementation yet to be done?
I'm sorry that my knowledge of 3D object manipulation is extremely low.
Thanks for the comprehension.

**Comment by andresoviedo** [comment]
Hi @victorcs85  I loaded your file. The problem was that the vertices were defined with more than 1 space between the coordinates. I fixed that. So now you should be able to load the model with the "Load Model" feature.  I also improved the handling of errors so the errors can be debugged easier.  Thank you for using the app :)
Kind regards
