### ISSUE TITLE
How to translate 3D model in view?

### ISSUE THREAD

**Issue by alexdar94** [andresoviedo/android-3D-model-viewer#20]
I want to position a model on screen by specifying it's x position and y position on screen. I have attempted to apply `Matrix.translateM` on `modelMatrix` but the result turned out to be the model was rotated around the origin, not translated to a new x, y position on screen. May I know how to properly position the model on screen? How to translate the model on (x,y) plane with fixed view and projection?

Object3DImpl
```
public float[] getMMatrix(Object3DData obj) {
	// calculate object transformation
	Matrix.setIdentityM(mMatrix, 0);
	...
	if (obj.getPosition() != null) {
		Matrix.translateM(mMatrix, 0, obj.getPositionX(), obj.getPositionY(), obj.getPositionZ());
                // Line added to translate model
		Matrix.translateM(mMatrix, 0, -0.5f, 0, 0);
	}
	return mMatrix;
}
```

Thank you.

**Comment by alexdar94** [comment]
@

**Comment by andresoviedo** [comment]
Hello body. In order to position object on space, you would have to use method provided on [Object3DData#setPosition(float[])](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/model/Object3DData.java#L227).

There is an usage example on [ExampleSceneLoader:57](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/services/ExampleSceneLoader.java#L57). 

If you have further questions don't hesitate and ask.

Kind regards
Andrés

**Comment by alexdar94** [comment]
Hi Andrés, thank you so much for your reply! I will try it out, thanks!
