### ISSUE TITLE
Why i can't move the camera on ToyPlane.obj?

### ISSUE THREAD

**Issue by panshen** [andresoviedo/android-3D-model-viewer#22]
Why i can't move the camera on ToyPlane.obj?

**Comment by andresoviedo** [comment]
Can you zoom out and then rotate?

**Comment by panshen** [comment]
Only rotate gesture can work,but in cubes.obj all gestures is work fine.

**Comment by andresoviedo** [comment]
Weird. Does the "Demo" works for you? Please try all other models and tell me in which ones the camera doesn't work, besides of the ToyPlane.obj.
Try all movements. Zoom, translate and rotate. Also load your own model and test it. You tell me.
Because this is a weird issue, would you mind recording the screen and upload the video so we can debug it? Thank you

**Comment by panshen** [comment]
Much thanks for you great work,here is the screen record i just uploaded onto youtube https://www.youtube.com/watch?v=ypZB6fCwJPg ,as you can see the gestures only work fine on the cube.obj looks like.On the other models it dosen't work corrctly all the time.It's weird ,hope you can fix it .Thanks again.

**Comment by andresoviedo** [comment]
Hi @panshen  Thank you for your feedback.  As far as I can see you have introduced a new "Girl" model into the app. Could you try to modify the scale of the loaded object to see if the problem you have is because the camera gets trapped inside the bounds of the model.
Is would just be a matter of modifying the scale (for example 1.0f) once the model is loaded, here in this line and tell me what happens?
https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/services/SceneLoader.java#L123
kind regards

**Comment by panshen** [comment]
I've tried you suggested ,but it doesn't work ,and i notice that the Camera.isOutOfBounds() function always return true and with a debug message at this line https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/entities/Camera.java#L201 .
In the meantime, i have run this demo in my emulator which running API 26 and everything is ok (include translate ,rotate and zoom ) .
There supposed have something subtle API implement difference between API 24 and 26 i guess.

**Comment by Marunizer** [comment]
Hello, 
This caught my interest because I've been experiencing the exact same scenario. 

Any time I try to run the app on API 24 whether it's Android 7 or 7.1,  I  don't have access to  rotations/zoom unless i'm on the cube object models. 

When I run the app on every other API however, all the models works fine.
Was this ever fixed for API 24? If not, I would like to look into it after being pointed in the right direction (:

side note: thanks for making such an awesome app !
