### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by lisongting** [andresoviedo/android-3D-model-viewer#30]
I found it too hard to transplant and use your code  .For example ,I just want to use some of your classes  to display 3D models in my application,but I have to import many another classes as dependence. If I want to use `SceneLoader` ,but `SceneLoader` has reference to `ModelActivity` ,It isn't a good design as far as I am concerned.

In other words ,The coupling degree in your code may be very high.

Could you please make your classes into .jar files ?So that we can import your classes and use it easily.

Could you please upload your code to jCenter that we can import your code to our applications by adding dependence to build.gradle  ?

**Comment by andresoviedo** [comment]
Yes. I know. The code is a bit coupled and messy. A full code refactoring is pending to be done.

**Comment by andresoviedo** [comment]
Some refactoring performed.  It still can be improved, but since the issue was opened, now it is a bit better, like:
*  engine library externalized
*  package organization

There is probably still some coupling between components but this is a start.
If you need further support on this, please reopen issue.
